apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mv-tls-secret
    type: kubernetes.io/tls
    files:
      - tls.crt=server.crt
      - tls.key=server.key
generatorOptions:
  disableNameSuffixHash: true
resources:
  - volume.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml

