apiVersion: v1
kind: PersistentVolume
metadata:
  name: mv-mn-db
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/milvus/minio/data
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mv-mn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 20Gi