apiVersion: v1
kind: Secret
metadata:
  name: langchain
type: Opaque
data:
  zilliz-token: ZGI3YzkxMGNjNGY2ODlkZjUzMTBjMTE1OWY5ZTJhZmIyOTVkYzQyZjE1MTE2MTZiNThlOTdlYThjMTZjZjE4YTViZTU4Yzg3NDNjMGUwNDliM2I2MWJjZWZhMTIwNDJhOTk5Y2QzNDQ=
  lf-secret-key: c2stbGYtNGI0NDlhODAtN2UxYy00YmMzLWE0OWEtNWYwYjFhMWI5OTkx
  lf-public-key: cGstbGYtYTdlMjFiZGUtNTgwZi00NTZiLTllMjgtNzYxMmZlMjMwYzRh
