apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: docproc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: docproc
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60

