apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot-frontend
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml
  - hpa.yaml
