apiVersion: v1
kind: Secret
metadata:
  name: webui-minio
type: Opaque
data:
  access-key: dDNLYUhjMjdtQ0FMb05QMEt6R2k=
  secret-key: ZFprWU5LaEF1ekFTbjRQRklKNDF0MURMa0RCRzVFOWdrYzZUUDdCRg==
  bucket-name: ZG9jLXByb2M=
