apiVersion: v1
kind: PersistentVolume
metadata:
  name: milvus-lite-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/milvus-lite
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-lite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 10Gi



