apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: object-storage
secretGenerator:
  - name: minio-tls-secret
    type: kubernetes.io/tls
    files:
      - tls.crt=server.crt
      - tls.key=server.key
generatorOptions:
  disableNameSuffixHash: true
