apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatbot-frontend
secretGenerator:
  - name: rag-tls-secret
    type: kubernetes.io/tls
    files:
      - tls.crt=server.crt
      - tls.key=server.key

generatorOptions:
  disableNameSuffixHash: true

