apiVersion: v1
kind: PersistentVolume
metadata:
  name: ob-mn-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/object-storage 
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ob-mn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 20Gi



