apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: lf-encryption
    files:
      - encryption-key=encryption_key.txt
      - salt=salt.txt

generatorOptions:
  disableNameSuffixHash: true

resources:
  - secret.yaml

