apiVersion: v1
kind: Secret
metadata:
  name: lf-ch-db
type: Opaque
data:
  db-user: a2V5Y2xvYWstYWRtaW4=
  db-password: cXF3d2VlZWVlcnR5b3A=

---

apiVersion: v1
kind: Secret
metadata:
  name: lf-mn-db
type: Opaque
data:
  db-user: a2V5Y2xvYWstYWRtaW4=
  db-password: cXF3d2VlZWVlcnR5b3A=


---

apiVersion: v1
kind: Secret
metadata:
  name: lf-pg-db
type: Opaque
data:
  db-user: a2V5Y2xvYWstYWRtaW4=
  db-password: cXF3d2VlZWVlcnR5b3A=


---

apiVersion: v1
kind: Secret
metadata:
  name: lf-rd-db
type: Opaque
data:
  db-password: cXF3d2VlZWVlcnR5b3A=


---


apiVersion: v1
kind: Secret
metadata:
  name: lf-wb-pass
type: Opaque
data:
  lf-user: a2V5Y2xvYWstYWRtaW4=
  lf-password: cXF3d2VlZWVlcnR5b3A=