apiVersion: v1
kind: PersistentVolume
metadata:
  name: lf-pg-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/langfuse/pg
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lf-pg-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 5Gi



