apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      category: redis
  template:
    metadata:
      labels:
        category: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          command:
          - redis-server
          args:
          - --requirepass
          - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          resources:
            requests:
              cpu: "2"
              memory: 8Gi
            limits:
              cpu: "2"
              memory: 8Gi
          ports:
            - containerPort: 6379
