apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  clusterIP: None
  selector:
    category: redis
  ports:
    - port: 6379
      name: redis


--- 


apiVersion: v1
kind: Service
metadata:
  name: redis-0
spec:
  clusterIP: None
  selector:
    app: redis-0
  ports:
    - port: 6379
      name: redis


--- 


apiVersion: v1
kind: Service
metadata:
  name: redis-1
spec:
  clusterIP: None
  selector:
    app: redis-1
  ports:
    - port: 6379
      name: redis

--- 

apiVersion: v1
kind: Service
metadata:
  name: redis-2
spec:
  clusterIP: None
  selector:
    app: redis-2
  ports:
    - port: 6379
      name: redis

---

apiVersion: v1
kind: Service
metadata:
  name: redis-3
spec:
  clusterIP: None
  selector:
    app: redis-3
  ports:
    - port: 6379
      name: redis


--- 


apiVersion: v1
kind: Service
metadata:
  name: redis-4
spec:
  clusterIP: None
  selector:
    app: redis-4
  ports:
    - port: 6379
      name: redis

--- 

apiVersion: v1
kind: Service
metadata:
  name: redis-5
spec:
  clusterIP: None
  selector:
    app: redis-5
  ports:
    - port: 6379
      name: redis