kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  ssl-protocols: "TLSv1.2 TLSv1.3"  
  ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384"
  proxy-buffering: "off"
  proxy-request-buffering: "off"
  proxy-read-timeout: "600"
  proxy-send-timeout: "600"
  proxy-http-version: "1.1"
  proxy-body-size: 20m
