apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-ingress

generatorOptions:
  disableNameSuffixHash: true

resources:
  - service-account.yaml
  - rbac.yaml
  - configmap.yaml
  - ingress-class.yaml
  - https://raw.githubusercontent.com/nginxinc/kubernetes-ingress/v3.6.1/deploy/crds.yaml
  - deployment.yaml
  - service.yaml