apiVersion: apps/v1
kind: Deployment
metadata:
  name: lf-wb

spec:
  replicas: 4
  selector:
    matchLabels:
      app: lf-wb
  template:
    metadata:
      labels:
        app: lf-wb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - worker2 
      containers:
      - name: langfuse-web
        image: langfuse/langfuse:3
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
        envFrom:
          - configMapRef:
              name: lf-common
          - configMapRef:
              name: lf-web
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: lf-wb-creds
                key: na-secret
          - name: LANGFUSE_INIT_USER_NAME
            valueFrom:
              secretKeyRef:
                name: lf-wb-creds
                key: lf-user
          - name: LANGFUSE_INIT_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lf-wb-creds
                key: lf-password
          - name: CLICKHOUSE_USER
            valueFrom:
              secretKeyRef:
                name: lf-ch-db
                key: db-user
          - name: CLICKHOUSE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lf-ch-db
                key: db-password
          - name: LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: lf-mn-db
                key: db-password
          - name: LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: lf-mn-db
                key: db-password
          - name: LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: lf-mn-db
                key: db-password
          - name: DATABASE_HOST
            value: lf-pg-db
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: lf-pg-db
                key: db-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lf-pg-db
                key: db-password
          - name: DATABASE_NAME
            value: postgres
          - name: REDIS_AUTH
            valueFrom:
              secretKeyRef:
                name: lf-rd-db
                key: db-password
          - name: SALT
            valueFrom:
              secretKeyRef:
                name: lf-encryption
                key: salt    
          - name: ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: lf-encryption
                key: encryption-key

