apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mv-et-db
spec:
  serviceName: mv-et-db
  replicas: 1
  selector:
    matchLabels:
      app: mv-et-db
  template:
    metadata:
      labels:
        app: mv-et-db
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.0
          command: ["etcd", "-advertise-client-urls=http://0.0.0.0:2379", "-listen-client-urls=http://0.0.0.0:2379", "--data-dir", "/etcd"]
          env:
            - name: ETCD_AUTO_COMPACTION_MODE
              value: revision
            - name: ETCD_AUTO_COMPACTION_RETENTION
              value: "1000"
            - name: ETCD_QUOTA_BACKEND_BYTES
              value: "4294967296"
          resources:
            requests:
              cpu: "4"
              memory: "20Gi"
            limits:
              cpu: "4"
              memory: "20Gi"
          ports:
            - containerPort: 2379
          volumeMounts:
            - name: mv-et-data
              mountPath: /etcd
      volumes:
        - name: mv-et-data
          persistentVolumeClaim:
            claimName: mv-et-pvc
