apiVersion: v1
kind: PersistentVolume
metadata:
  name: mv-et-db
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/milvus/etcd
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mv-et-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 15Gi