apiVersion: v1
kind: Service
metadata:
  name: lf-ch-db
spec:
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      name: hc
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: db
  selector:
    app: lf-ch-db
