apiVersion: v1
kind: PersistentVolume
metadata:
  name: lf-ch-logs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/langfuse/ch/logs
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lf-ch-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lf-ch-data-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /mnt/data/langfuse/ch/data
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lf-ch-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  resources:
    requests:
      storage: 5Gi




